export const mediaWikiUrlRoot: string = 'https://en.wikipedia.org/w/api.php';

export const wordList: string[] = [
    'Apple',
    'Kyoto',
    'Tetris',
    'Nintendo',
    'Steampunk',
    'Avatar: The Last Airbender',
    'Mount Kilimanjaro',
    'The Legend of Zelda: Tears of the Kingdom',
    'Animal Crossing',
    'Cyberpunk',
    'Tokyo',
    'Minecraft',
    'William Shakespeare',
    'Atlantis',
    'Pac-Man',
    'Star Wars',
    'Stonehenge',
    'Fortnite',
    'Leonardo da Vinci',
    'Machu Picchu',
    'Spider-Man 2 (2023 video game)',
    'Avengers (Marvel Cinematic Universe)',
    'Respiratory system',
    'Ice cream',
    'New Jersey Institute of Technology',
    'Edgar Allan Poe',
    'Pompeii',
    'The Walt Disney Company',
    'The Lord of the Rings',
    'Palace of Versailles',
    'Super Mario',
    'Alfred Hitchcock',
    'Easter Island',
    'Assassin\'s Creed',
    'The Matrix',
    'Universe',
    'Call of Duty',
    'Tea',
    'Niagara Falls',
    'Halo',
    'Cinema Paradiso',
    'El Dorado',
    'The Umbrella Academy',
    'Stranger Things',
    'Great Sphinx of Giza',
    'The Elder Scrolls V: Skyrim',
    'Frida Kahlo',
    'Petra',
    'Greece',
    'The X-Files',
    'Great Wall of China',
    'Portal (video game)',
    'The Sopranos',
    'Battle of the Alamo',
    'Donkey Kong',
    'New Jersey',
    'Atlantis',
    'Black Mirror',
    'Christmas',
    'The Pyramids',
    'Cobra Kai',
    'The Beatles',
    'Acropolis',
    'Witcher',
    'The Hunger Games',
    'Machu Picchu',
    'Sodium chloride',
    'Blade Runner',
    'Taj Mahal',
    'Sonic the Hedgehog',
    'Harry Potter',
    'Area 51',
    'Charles Darwin',
    'Paris',
    'Pompeii',
    'Stranger Things',
    'Sphere (venue)',
    'Game of Thrones',
    'Salvador Dalí',
    'Stonehenge',
    'The Elder Scrolls',
    'Texas',
    'Computer',
    'Big Ben',
    'Disneyland',
    'Aztecs',
    'Radix sort',
    'Hip hop music',
    'Nuclear fallout',
    'David Bowie',
    'Great Wall of China',
    'Ocean',
    'Hero',
    'Leonardo da Vinci',
    'Poaceae',
    'Star Trek',
    'Zedd'
];