export const wordList: string[] = [
    'Apple',
    'Kyoto',
    'Tetris',
    'Nintendo',
    'Steampunk',
    'Avatar: The Last Airbender',
    'Mount Kilimanjaro',
    'The Legend of Zelda: Tears of the Kingdom',
    'Animal Crossing',
    'Cyberpunk',
    'Tokyo',
    'Minecraft',
    'William Shakespeare',
    'Atlantis',
    'Pac-Man',
    'Star Wars',
    'Stonehenge',
    'Fortnite',
    'Leonardo da Vinci',
    'Machu Picchu',
    'Spider-Man 2 (2023 video game)',
    'Avengers (Marvel Cinematic Universe)',
    'Respiratory system',
    'Ice cream',
    'New Jersey Institute of Technology',
    'Edgar Allan Poe',
    'Pompeii',
    'The Walt Disney Company',
    'The Lord of the Rings',
    'Palace of Versailles',
    'Super Mario',
    'Alfred Hitchcock',
    'Easter Island',
    'Assassin\'s Creed',
    'The Matrix',
    'Universe',
    'Call of Duty',
    'Tea',
    'Niagara Falls',
    'Halo',
    'Cinema Paradiso',
    'El Dorado',
    'The Umbrella Academy',
    'Stranger Things',
    'Great Sphinx of Giza',
    'The Elder Scrolls V: Skyrim',
    'Frida Kahlo',
    'Petra',
    'Greece',
    'The X-Files',
    'Great Wall of China',
    'Portal (video game)',
    'The Sopranos',
    'Battle of the Alamo',
    'Donkey Kong',
    'New Jersey',
    'Atlantis',
    'Black Mirror',
    'Christmas',
    'The Pyramids',
    'Cobra Kai',
    'The Beatles',
    'Acropolis',
    'Witcher',
    'The Hunger Games',
    'Machu Picchu',
    'Sodium chloride',
    'Blade Runner',
    'Taj Mahal',
    'Sonic the Hedgehog',
    'Harry Potter',
    'Area 51',
    'Charles Darwin',
    'Paris',
    'Pompeii',
    'Stranger Things',
    'Sphere (venue)',
    'Game of Thrones',
    'Salvador Dalí',
    'Stonehenge',
    'The Elder Scrolls',
    'Texas',
    'Computer',
    'Big Ben',
    'Disneyland',
    'Aztecs',
    'Radix sort',
    'Hip hop music',
    'Nuclear fallout',
    'David Bowie',
    'Great Wall of China',
    'Ocean',
    'Hero',
    'Leonardo da Vinci',
    'Poaceae',
    'Star Trek',
    'Zedd'
];

export const moviesShowsList: string[] = [
    'Spider-Man: Across the Spider-Verse',
    'The Super Mario Bros. Movie',
    "Five Nights at Freddy's (film)",
    'Barbie (film)',
    'Oppenheimer (film)',
    'Avatar (2009 film)',
    'Avengers: Endgame',
    'Titanic (1997 film)',
    'Jurassic World',
    'Star Wars (film)',
    'The Lion King',
    'Frozen (2013 film)',
    'Beauty and the Beast (1991 film)',
    'Incredibles 2',
    'WALL-E',
    "Harry Potter and the Philosopher's Stone (film)",
    'Shrek 2',
    'Spy Kids (film)',
    'The Dark Knight',
    'Breaking Bad',
    'Avatar: The Last Airbender',
    'Rick and Morty',
    'SpongeBob SquarePants',
    'Phineas and Ferb',
    'Kitchen Nightmares',
    'The Nightmare Before Christmas',
    'Coraline (film)',
    'Toy Story',
    'The Fairly OddParents',
    'Your Name',
    'The Umbrella Academy (TV series)',
    'Invincible (TV series)',
    'Ready Player One (film)',
    'My Neighbor Totoro',
    'Total Drama Island',
    'The Walking Dead (TV series)',
    'Puss in Boots: The Last Wish',
    'Gravity Falls',
    'The Simpsons',
    'Forrest Gump',
    'The Matrix',
    'Crazy Rich Asians (film)',
    'Spider-Man: No Way Home',
    'The Terminator',
    'Stranger Things',
    'Loki (TV series)',
    'Bee Movie',
    'Megamind',
    'Squid Game',
    'The Karate Kid',
    'Ponyo',
    'Courage the Cowardly Dog',
    'Ben 10',
    'Adventure Time',
    'Regular Show',
    'iCarly',
    'Big Time Rush',
    'The Amazing World of Gumball',
    'Turning Red',
    'Cars (film)',
    'Family Guy',
    'The Powerpuff Girls',
    'Iron Man (2008 film)',
    'Inception',
    'The Great Gatsby (2013 film)',
    'Minions (film)',
    'The Batman (film)',
    'Sonic the Hedgehog (film)',
    'Cobra Kai',
    'Pokémon: The First Movie',
    'Scooby-Doo',
    'The Amazing Spider-Man (film)',
    'Godzilla (franchise)',
    'Shang-Chi and the Legend of the Ten Rings',
    'How to Train Your Dragon (film)',
    'The Lorax (film)',
    'National Treasure (film)',
    'Monsters, Inc.',
    'Doctor Strange in the Multiverse of Madness',
    'Spider-Man (2002 film)',
    'The Suite Life of Zack & Cody',
    'Everything Everywhere All at Once',
    'Zootopia',
    'Parasite (2019 film)',
    'The Hunger Games (film)',
    'The Maze Runner (film)',
    'Wizards of Waverly Place',
    'Game of Thrones',
    'It (2017 film)',
    'The Office (American TV series)',
    'Friends',
    'Ralph Breaks the Internet',
    'Doctor Who',
    'Willy Wonka & the Chocolate Factory',
    'Soul (2020 film)',
    'Encanto',
    'The Jetsons',
    "Foster's Home for Imaginary Friends",
    'The Adventures of Jimmy Neutron, Boy Genius',
    'Ratatouille (film)'    
];

export const historyList: string[] = [
	'Alexander the Great',
	'Great Pyramid of Giza',
	'Roman Republic',
	'Mesopotamia',
	'Great Wall of China',
	'Crucifixion of Jesus',
	'Roman Empire',
	'Charlemagne',
	'Battle of Hastings',
	'Magna Carta',
	'Black Death in England',
	'Renaissance',
	'Fall of Constantinople',
	'Christopher Columbus',
	'Reformation',
	'Taj Mahal',
	'English Civil War',
	'Age of Enlightenment',
	'American Revolution',
	'French Revolution',
	'Industrial Revolution',
	'Haitian Revolution',
	'Napoleonic Wars',
	'Charles Darwin',
	'American Civil War',
	'Meiji Restoration',
	'Alexander Graham Bell',
	'World War I',
	'Russian Revolution',
	'Wall Street Crash of 1929',
	'World War II',
	'The Holocaust',
	'Atomic bombings of Hiroshima and Nagasaki',
	'United Nations',
	'Decolonisation of Africa',
	'Civil rights movement',
	'Cuban Missile Crisis',
	'Apollo 11',
	'Berlin Wall',
	'Apartheid',
	'September 11 attacks',
	'Arab Spring',
	'Confucius',
	'Julius Caesar',
	'Cleopatra',
	'Jesus',
	'Muhammad',
	'Joan of Arc',
	'Leonardo da Vinci',
	'Michelangelo',
	'Galileo Galilei',
	'Isaac Newton',
	'Marie Antoinette',
	'Napoleon',
	'George Washington',
	'Abraham Lincoln',
	'Mahatma Gandhi',
	'Winston Churchill',
	'Albert Einstein',
	'Franklin D. Roosevelt',
	'Martin Luther King Jr.',
	'Nelson Mandela',
	'Margaret Thatcher',
	'Mother Teresa',
	'Rosa Parks',
	'Mikhail Gorbachev',
	'Steve Jobs',
	'Barack Obama',
	'Elizabeth II',
	'Diana, Princess of Wales',
	'Printing press',
	'Salem witch trials',
	'Thirty Years\' War',
	'Boston Tea Party',
	'California Gold Rush',
	'Taiping Rebellion',
	'German Empire',
	'Boxer Rebellion',
	'Sinking of the Titanic',
	'Zimmermann Telegram',
	'Treaty of Versailles',
	'Great Depression',
	'Dust Bowl',
	'Spanish Civil War',
	'Kristallnacht',
	'Normandy landings',
	'Marshall Plan',
	'Korean War',
	'Suez Crisis',
	'Cuban Revolution',
	'Vietnam War',
	'Prague Spring',
	'Apollo 13',
	'Watergate scandal',
	'Iranian Revolution',
	'Falklands War',
	'Chernobyl disaster',
	'Rwandan genocide',
	'Vikings',
	'Aztecs',
	'Gulf War',
];

export const mathScienceList: string[] = [
    'Arithmetic',
    'Algebra',
    'Geometry',
    'Calculus',
    'Probability',
    'Statistics',
    'Trigonometry',
    'Number theory',
    'Linear algebra',
    'Differential equation',
    'Combinatorics',
    'Cryptography',
    'Mathematical logic',
    'Set theory',
    'Game theory',
    'Pushdown automaton',
    'Complex analysis',
    'Graph theory',
    'Vector',
    'Prime number',
    'Natural number',
    'Discrete mathematics',
    'Mathematical model',
    'Number',
    'Logic gate',
    'Boolean algebra',
    'Gradient',
    'Discrete Fourier transform',
    'Fourier analysis',
    'Vector calculus',
    'Differential geometry',
    'Radix',
    "Pascal's triangle",
    'Bayesian probability',
    'Riemann hypothesis',
    'Knot theory',
    'Golden ratio',
    'Binary classification',
    'Physics',
    'Chemistry',
    'Biology',
    'Astronomy',
    'Earth science',
    'Environmental science',
    'Geology',
    'Paleontology',
    'Meteorology',
    'Quantum mechanics',
    'General relativity',
    'Atomic theory',
    'Genetics',
    'Evolution',
    'Ecology',
    'Plate tectonics',
    'Climate change',
    'Big Bang',
    'Particle physics',
    'Microbiology',
    'Astrophysics',
    'Neuroscience',
    'Nanotechnology',
    'Space exploration',
    'String theory',
    'Thermodynamics',
    'Chemical reaction',
    'Human evolution',
    'Environmental protection',
    'Solar System',
    'Cell (biology)',
    'Biotechnology',
    'Artificial intelligence',
    'Black hole',
    'Quantum field theory',
    'Genetic engineering',
    'Climatology',
    'Ecology',
    'Cell biology',
    'Oceanography',
    'Artificial life',
    'Astrobiology',
    'Cybernetics',
    'Evolutionary psychology',
    'Cosmology',
    'Chaos theory',
    'Biochemistry',
    'Biodiversity',
    'Nuclear physics',
    'Cognitive science',
    'Optics',
    'Materials science',
    'Neurology',
    'Wave',
    'Quantum computing',
    'Ethology',
    'Immunology',
    'Behavioral ecology',
    'Turing machine',
    'P versus NP problem',
    'Svelte',
    'Typescript'
];

export const sportsMemesVideoGamesAnimeList: string[] = [
    'New York Yankees',
    'Boston Red Sox',
    'Houston Astros',
    'Los Angeles Dodgers',
    'Chicago Cubs',
    'St. Louis Cardinals',
    'San Francisco Giants',
    'Atlanta Braves',
    'Philadelphia Phillies',
    'Cleveland Guardians',
    'New York Mets',
    'Los Angeles Lakers',
    'Boston Celtics',
    'Golden State Warriors',
    'Chicago Bulls',
    'Miami Heat',
    'New York Knicks',
    'Green Bay Packers',
    'Dallas Cowboys',
    'Pittsburgh Steelers',
    'San Francisco 49ers',
    'New York Giants',
    'New York Jets',
    'Cleveland Browns',
    'Detroit Red Wings',
    'Montreal Canadiens',
    'Toronto Maple Leafs',
    'Boston Bruins',
    'New York Rangers',
    'Philadelphia Flyers',
    'Pittsburgh Penguins',
    'National Football League',
    'Major League Baseball',
    'NBA (National Basketball Association)',
    'NCAA Division I Men\'s Basketball Tournament',
    'Super Bowl',
    'World Series',
    'NCAA Division I Football Bowl Subdivision',
    'Olympic Games',
    'History of American football',
    'Internet meme',
    'Rickrolling',
    'Distracted Boyfriend',
    'Pepe the Frog',
    'Nyan Cat',
    'Doge',
    'Mocking SpongeBob',
    'Trollface',
    'Harambe',
    'This is Fine',
    'Two Buttons',
    'Bad Luck Brian',
    'Success Kid',
    'Distracted Girlfriend',
    'Keyboard Cat',
    'Grumpy Cat',
    'Overly Attached Girlfriend',
    'Hide the Pain Harold',
    'Arthur Fist',
    'Salt Bae',
    'The Dress',
    'Cash Me Ousside, How \'Bout Dat?',
    'Y U No',
    'Wojak',
    'Woman Yelling at a Cat',
    'Chocolate Rain',
    'All Your Base Are Belong to Us',
    'Charlie Bit My Finger',
    'I Can Has Cheezburger?',
    'Friday',
    'Gonna Tell My Kids',
    'The Most Interesting Man in the World',
    'Chuck Norris Facts',
    'Video game',
    'The Legend of Zelda',
    'Super Mario Bros.',
    'Minecraft',
    'Fortnite',
    'Grand Theft Auto V',
    'Pokémon',
    'Call of Duty: Modern Warfare',
    'The Witcher 3: Wild Hunt',
    'Overwatch',
    'World of Warcraft',
    'Red Dead Redemption 2',
    'Final Fantasy VII',
    'League of Legends',
    'Counter-Strike: Global Offensive',
    'Animal Crossing: New Horizons',
    'Fallout 4',
    'Super Smash Bros. Ultimate',
    'The Elder Scrolls V: Skyrim',
    'Halo: Combat Evolved',
    'Mass Effect 2',
    'Dark Souls',
    'Doom (2016)',
    'The Last of Us',
    'The Sims',
    'Street Fighter II',
    'Tetris',
    'Pac-Man',
    'FIFA series',
    'Assassin\'s Creed',
    'Sonic the Hedgehog (2006)',
    'Star Wars Jedi: Survivor',
    'Dragon Ball',
    'Kaguya-sama: Love Is War',
    'Naruto',
    'One Piece',
    'My Hero Academia',
    'Attack on Titan',
    'Death Note',
    'Fullmetal Alchemist: Brotherhood',
    'Sword Art Online',
    'Demon Slayer: Kimetsu no Yaiba',
    'Neon Genesis Evangelion',
    'One Punch Man',
    'Hunter x Hunter',
    'Steins;Gate',
    'Cowboy Bebop',
    'Dragon Ball Z',
    'Bleach',
    'Code Geass'
];

export const combinedList = Array.from(
    new Set([...wordList, ...historyList, ...sportsMemesVideoGamesAnimeList, ...mathScienceList]).values()
);