export const wordList: string[] = [
    'Apple',
    'Kyoto',
    'Tetris',
    'Nintendo',
    'Steampunk',
    'Avatar: The Last Airbender',
    'Kilimanjaro',
    'The Legend of Zelda: Tears of the Kingdom',
    'Animal Crossing',
    'Cyberpunk',
    'Tokyo',
    'Minecraft',
    'Shakespeare',
    'Atlantis',
    'Pac-Man',
    'Star Wars',
    'Stonehenge',
    'Fortnite',
    'Da Vinci',
    'Machu Picchu',
    'Spider-Man 2 (2023 video game)',
    'Avengers (Marvel Cinematic Universe)',
    'Easter Island',
    'Respiratory system',
    'Ice cream',
    'New Jersey Institute of Technology',
    'Edgar Allan Poe',
    'Pompeii',
    'The Walt Disney Company',
    'Lord of the Rings',
    'Versailles',
    'Super Mario',
    'Hitchcock',
    'Easter Island',
    'Assassin\'s Creed',
    'The Matrix',
    'Universe',
    'Call of Duty',
    'Tea',
    'Niagara Falls',
    'Halo',
    'Cinema Paradiso',
    'El Dorado',
    'The Umbrella Academy',
    'Stranger Things',
    'The Sphinx',
    'Skyrim',
    'Frida Kahlo',
    'Petra',
    'Greece',
    'The X-Files',
    'Great Wall of China',
    'Portal (video game)',
    'Shakespearean Tragedy',
    'The Sopranos',
    'The Alamo',
    'Donkey Kong',
    'New Jersey',
    'Atlantis',
    'Black Mirror',
    'Christmas',
    'The Pyramids',
    'Cobra Kai',
    'The Beatles',
    'Acropolis',
    'Witcher',
    'The Hunger Games',
    'Machu Picchu',
    'Sodium chloride',
    'Blade Runner',
    'Taj Mahal',
    'Sonic the Hedgehog',
    'Harry Potter',
    'Area 51',
    'Charles Darwin',
    'Paris',
    'Pompeii',
    'Stranger Things',
    'Sphere (venue)',
    'Game of Thrones',
    'Salvador Dali',
    'Stonehenge',
    'Elder Scrolls',
    'Texas',
    'Computer',
    'Big Ben',
    'Disneyland',
    'Aztecs',
    'Radix sort',
    'Hip hop',
    'Fallout',
    'David Bowie',
    'Great Wall of China',
    'Ocean',
    'Hero',
    'Leonardo da Vinci',
    'Grass',
    'Star Trek',
    'Zedd'
];