class SetWords {
    public wordList: string[] = [
        'Kyoto',
        'Tetris',
        'Chernobyl',
        'Steampunk',
        'Avatar',
        'Kilimanjaro',
        'Zelda',
        'Casablanca',
        'Cyberpunk',
        'Tokyo',
        'Minecraft',
        'Shakespeare',
        'Atlantis',
        'Pac-Man',
        'Star Wars',
        'Stonehenge',
        'Fortnite',
        'Da Vinci',
        'Machu Picchu',
        'Bioshock',
        'Tarantino',
        'Easter Island',
        'World of Warcraft',
        'Game of Thrones',
        'Louvre',
        'Tetris Effect',
        'Edgar Allan Poe',
        'Pompeii',
        'Final Fantasy',
        'Lord of the Rings',
        'Versailles',
        'Super Mario',
        'Hitchcock',
        'Easter Island',
        'Assassin\'s Creed',
        'The Matrix',
        'Angkor Wat',
        'Call of Duty',
        'Quentin Tarantino',
        'Niagara Falls',
        'Halo',
        'Stanley Kubrick',
        'El Dorado',
        'Mass Effect',
        'Stranger Things',
        'The Sphinx',
        'Skyrim',
        'Frida Kahlo',
        'Petra',
        'Resident Evil',
        'The X-Files',
        'Great Wall of China',
        'Portal',
        'Shakespearean Tragedy',
        'The Sopranos',
        'The Alamo',
        'Donkey Kong',
        'Edgar Allan Poe',
        'Atlantis',
        'Black Mirror',
        'Easter Island',
        'Twin Peaks',
        'The Pyramids',
        'Bioshock Infinite',
        'The Beatles',
        'Acropolis',
        'Witcher',
        'Tim Burton',
        'Machu Picchu',
        'StarCraft',
        'Blade Runner',
        'Taj Mahal',
        'Sonic the Hedgehog',
        'Harry Potter',
        'Area 51',
        'Kingdom Hearts',
        'Tarantino Films',
        'Pompeii',
        'Stranger Things',
        'Louvre Museum',
        'Game of Thrones',
        'Salvador Dali',
        'Stonehenge',
        'Elder Scrolls',
        'Tim Burton Films',
        'Easter Island Statues',
        'Quentin Tarantino',
        'Disneyland',
        'Diablo',
        'David Lynch',
        'Angkor Wat Temple',
        'Fallout',
        'David Bowie',
        'Great Wall of China',
        'Resident Evil Games',
        'Twin Peaks TV Show',
        'Leonardo da Vinci',
        'Machu Picchu Ruins',
        'Star Trek',
        'Zedd'
    ];

    rtnSetWords(): string[] {
        return this.wordList;
    }
}
export const setWords = new SetWords();